import {
  CandidateTrack,
  MusicContextSnapshot,
  MusicIntent,
  MusicProfile,
  QueuedTrack,
  normalizeSongTitle,
} from './music-types';
import { expandMusicIntent } from './music-intent-expander';
import { candidateGenerator } from './candidate-generator';
import { recommendationRanker } from './recommendation-ranker';
import { diversityController } from './diversity-controller';
import { musicProfileService } from './music-profile-service';
import { musicContextProvider } from './context-provider';
import { resolveMusicTrack } from '@/modules/media/music-resolver';
import { logger } from '@/lib/logging/logger';


export class AutoplayEngine {
  /**
   * Orchestrates full recommendation pipeline to produce clean, playable queued tracks.
   */
  async recommendNextTracks(params: {
    userId: string;
    intent: MusicIntent;
    currentTrack?: QueuedTrack | null;
    seedTrack?: QueuedTrack | null;
    playbackHistory?: QueuedTrack[];
    conversationId?: string;
    timezone?: string;
    count?: number;
  }): Promise<QueuedTrack[]> {
    const {
      userId,
      intent,
      currentTrack,
      seedTrack,
      playbackHistory = [],
      conversationId,
      timezone,
      count = 5,
    } = params;

    // 1. Context & Profile Snapshots & LLM Music Soundscape
    const [profile, context] = await Promise.all([
      musicProfileService.getProfile(userId),
      musicContextProvider.getContextSnapshot(userId, conversationId, timezone),
    ]);

    const soundscape = await expandMusicIntent(intent, context);

    // 2. Candidate Generation
    const rawCandidates = await candidateGenerator.generateCandidates({
      intent,
      soundscape,
      currentTrack,
      seedTrack,
      profile,
      context,
      limit: Math.max(20, count * 4),
    });

    if (rawCandidates.length === 0) {
      logger.warn('No candidates generated by candidate generator', { userId, intent });
      return [];
    }

    // 3. Recommendation Ranking
    const ranked = recommendationRanker.rank({
      candidates: rawCandidates,
      intent,
      soundscape,
      currentTrack,
      seedTrack,
      profile,
      context,
    });

    // 4. Diversity Constraints
    const recentTracks = [
      ...playbackHistory,
      ...(currentTrack ? [currentTrack] : []),
    ];

    const selectedRanked = diversityController.applyDiversity({
      ranked,
      recentTracks,
      explicitArtist: intent.artist,
      count,
    });

    // 5. Playable URL Resolution & QueuedTrack conversion
    const queued: QueuedTrack[] = [];
    const seenQueuedTitles = new Set<string>();
    const seenQueuedUrls = new Set<string>();

    if (currentTrack?.title) seenQueuedTitles.add(normalizeSongTitle(currentTrack.title));
    if (currentTrack?.audioUrl) seenQueuedUrls.add(currentTrack.audioUrl);
    if (seedTrack?.title) seenQueuedTitles.add(normalizeSongTitle(seedTrack.title));
    if (seedTrack?.audioUrl) seenQueuedUrls.add(seedTrack.audioUrl);

    for (const item of selectedRanked) {
      const cand = item.track;
      const norm = normalizeSongTitle(cand.title);
      if (norm && seenQueuedTitles.has(norm)) continue;

      let finalAudioUrl = cand.audioUrl;
      let finalSource = cand.source;
      let videoId = cand.videoId;

      // If direct audio URL was not already extracted during search, resolve it via music-resolver
      if (!finalAudioUrl) {
        try {
          const resolved = await resolveMusicTrack(`${cand.title} by ${cand.artist}`);
          if (resolved.success && resolved.audioUrl) {
            finalAudioUrl = resolved.audioUrl;
            finalSource = resolved.source;
            videoId = resolved.videoId;
          }
        } catch (err) {
          logger.warn('Audio URL pre-resolution failed for candidate', {
            title: cand.title,
            artist: cand.artist,
            err,
          });
        }
      }

      // Only queue tracks that have a playable stream or video fallback and aren't duplicates
      if (finalAudioUrl || videoId) {
        if (finalAudioUrl && seenQueuedUrls.has(finalAudioUrl)) continue;
        if (norm) seenQueuedTitles.add(norm);
        if (finalAudioUrl) seenQueuedUrls.add(finalAudioUrl);

        queued.push({
          id: cand.id,
          title: cand.title,
          artist: cand.artist,
          album: cand.album,
          audioUrl: finalAudioUrl,
          artworkUrl: cand.artworkUrl,
          duration: cand.duration,
          source: finalSource,
          videoId,
          explanation: item.reasons.join(' · ') || 'Autoplay recommendation',
        });

        logger.info('Autoplay candidate queued', {
          title: cand.title,
          artist: cand.artist,
          score: item.finalScore.toFixed(3),
          reasons: item.reasons,
        });
      }
    }

    return queued;
  }
}

export const autoplayEngine = new AutoplayEngine();
