import { z } from 'zod';
import { BaseIntegrationTool } from '../../integration-tool';
import { SerenityClient, SerenityIdeasQueue } from '../SerenityClient';

export class GetIdeasQueueTool extends BaseIntegrationTool<
  Record<string, never>,
  SerenityIdeasQueue
> {
  constructor(client: SerenityClient) {
    super({
      id: 'serenity.get_ideas_queue',
      name: 'serenity.get_ideas_queue',
      description:
        'Fetches the ordered backlog of upcoming video topic ideas waiting to be generated by the Serenity pipeline.',
      integrationId: 'serenity',
      category: 'PRODUCTIVITY',
      actionType: 'READ',
      riskLevel: 'SAFE',
      requiresConfirmation: false,
      inputSchema: z.object({}),
      executor: async () => {
        const queue = await client.getIdeasQueue();
        return {
          success: true,
          data: queue,
          message: `The Serenity ideas queue currently contains ${queue.count} upcoming topic(s). Next up: "${queue.ideas[0] || 'Queue empty'}".`,
        };
      },
    });
  }
}
